---
name: Pipeline para deploy da aplicação no GitHub Pages

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configurar Pages
        uses: actions/configure-pages@v3
      - name: Carregar artefatos do Pages
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      - name: Deploy no GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
...
